### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Form-Countdown#11]

**Comment by mathetos** [comment]
@ravinderk I think these are the main contenders:

* Donation Countdown
* Form Duration
* Form Countdown
* Donation Deadline

I think my vote is "Form Countdown" -- I think @kevinwhoffman is right that using the word "Form" helps clarify what the Add-on does better than "Donation". But @DevinWalker is right that people likely will be searching more for "Countdown" than "Deadline" or "Duration".

**Comment by DevinWalker** [comment]
Form Countdown it is
