### ISSUE TITLE
Add basic style to goal and duration end message

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Form-Countdown#16]
@mathetos you already created an issue for that on `Give`, so I think this can be a part of `Give` core and we can use same style for this message.

For ref: https://github.com/WordImpress/Give/issues/1504

**Comment by mathetos** [comment]
Except that we want to release this Addon this week and not wait for a Give Core update.

**Comment by mathetos** [comment]
This is just an idea for a basic style. 

![image](https://cloud.githubusercontent.com/assets/930724/23294917/abba9f54-fa22-11e6-972f-aa27fecb3d0c.png)

@kevinwhoffman @DevinWalker what would you guys suggest for basic styling around the "Duration Ended" message? The thought is that this message should stand out as different from normal form content, but we don't want it to be so opinionated that everyone ends up always changing it.

Thoughts?

**Comment by kevinwhoffman** [comment]
@mathetos My gut says this is too opinionated. I would leave the container styling out. The one change I would make is to wrap the entire message in a div with a class that can be targeted to achieve this type of styling if desired. Currently the message is just injected into the form without a container.

**Comment by kevinwhoffman** [comment]
![image](https://cloud.githubusercontent.com/assets/1938671/23315863/0f845cc8-fa96-11e6-8158-9459866aae83.png)

![image](https://cloud.githubusercontent.com/assets/1938671/23315905/3c66c03c-fa96-11e6-84b1-a21fb13e4413.png)

To clarify the above recommendation, the `h3` and both `p` elements should be wrapped in a `div` with class of `gfc-message`.

**Comment by mathetos** [comment]
Good feedback, I think that's wisdom, especially for a free plugin. Done!
