### ISSUE TITLE
Review Clock responsive design

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Form-Countdown#18]
<img width="838" alt="screen shot 2017-02-24 at 8 28 49 am" src="https://cloud.githubusercontent.com/assets/1784821/23288753/4bc67066-fa6b-11e6-988b-5467ab2b0dd4.png">

**Comment by mathetos** [comment]
Maybe related to tightening the CSS is getting the markup right. Currently there's a `<span>` wrapping several DIVs. 

![image](https://cloud.githubusercontent.com/assets/930724/23293807/287545d6-fa1d-11e6-9a9d-1c23a740383a.png)

**Comment by mathetos** [comment]
What I found in just fiddling a little is that the HEIGHT of the `.time.weeks` wrapper div is fixed at 95px, but the font-size of the actual numbers inside the `span`s is set to 2em, a relative unit. Here's a few things I think would help:

* Set the font-size for the whole div to 40px
* Set a `line-height: 0` for the whole div, then define the span.label to have a `line-height:1` It's kind of a pseudo-normalize technique
* define margin and padding for everything inside the wrapper div
* set the height for everything inside the div to "inherit".

Hopefully these precautions will go a long way if done well.
