### ISSUE TITLE
If Goal Reached the Clock should disappear

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Form-Countdown#20]
I think this result is not desired:
![image](https://cloud.githubusercontent.com/assets/930724/23294373/e814f7c2-fa1f-11e6-9c23-d91393184382.png)

This happens if you set a Goal, and enable the Clock, and the Goal is reached before the Duration ends. I think if the Goal is achieved and either the Goal Ended, or Duration Achieved messages are shown, then the clock should be removed.

**Comment by ravinderk** [comment]
@mathetos Done.

For Ref: https://github.com/WordImpress/Give-Form-Countdown/commit/bc5a15ab9a123ae2d1eb542b444f35ac56329a11
