### ISSUE TITLE
Display times in chronological order

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Form-Countdown#21]
## Issue Overview

The times as they appear now are out of order. 12:00 am does not follow 11:00 am and 12:00 pm does not follow 11:00 pm.

## Current Behavior

* Time defaults to 1:00 am.
* Illogical jump between 11:00 am and 12:00 am.
* Illogical jump between 11:00 pm and 12:00 pm.

## Expected Behavior

* Time should default to 12:00 am as first item in list.
* The list of times should follow a chronological order, beginning with 12:00 am (earliest time of day) and work up to 11:00 pm (latest time of day).

## Possible Solution

Order times chronologically as described above.

## Screenshots

Current behavior shown below.

![image](https://cloud.githubusercontent.com/assets/1938671/23313098/46cd093e-fa8a-11e6-933d-622fe9360440.png)

**Comment by mathetos** [comment]
@kevinwhoffman Good catch. Fixed both the order and defaulted to 6:00 p.m.
