### ISSUE TITLE
Label and description suggestions

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give-Form-Countdown#22]
@mathetos Label suggestions in red. Description suggestions in blue. Take as much or as little as you like from it.

* There was some language that implied the form always closes when the duration ends. I made that language more generic.
* Simplified labels and used consistent language (End Date, End Time, End Message, End Behavior). These are all settings that determine what happens when the duration ends.
* Applied a consistent structure to descriptions. Every description starts with an action verb followed by a description of what the setting does.

![image](https://cloud.githubusercontent.com/assets/1938671/23315230/5ba5ee76-fa93-11e6-9238-a5fbb607e365.png)

**Comment by mathetos** [comment]
Thanks @kevinwhoffman for putting that thought into these. I did all of them with only minor changes.
