### ISSUE TITLE
Give's Countdown and Donation Goal cannot do Kickstarter or Indiegogo like format

### ISSUE THREAD

**Issue by gordoncsmith** [WordImpress/Give-Form-Countdown#28]
I tried the Give-Form-Countdown along with your Donation Goal but they didn't enable me to do a Kickstarter or Indiegogo -like format that allows me have the Goal, the Countdown, and a Donate button displayed together.

Instead, I get the countdown and the donate button.   When you click the donate button it then shows the goal at the top of the popup for entering the details needed to make the donation,.

I sent screenshots of this to Jason Knill.   I can send them to anyone else if you give me an email address or some other mechanism.

I tried to attached the first screen shot using you attach file mechanism below.  Didn't seem to work.

Thanks,
- Gordon

![image](https://user-images.githubusercontent.com/31996347/37113967-d1ced546-21fb-11e8-86e7-e72f7488045d.png)

**Comment by gordoncsmith** [comment]
Here is the other screenshot:

![screenshot 2018-03-07 at 11 41 01 am](https://user-images.githubusercontent.com/31996347/37114196-86414a36-21fc-11e8-8005-930362500201.png)

**Comment by mathetos** [comment]
HI @gordoncsmith -- it looks like you're using the Modal display option. If you want to see them all on the same page, you should set the display method in your form to "All fields". See here:
![image](https://user-images.githubusercontent.com/930724/37115999-b5c3d454-2201-11e8-8253-b12ffc88f88c.png)

Let me know if that resolves this issue for you.

**Comment by gordoncsmith** [comment]
I'm actually using the Button display option.  I tried using the Modal but that didn't work either - as I recall it displayed the donation entry box and minimum accepted box which I don't want..   

I want it to look like Kickstarter, Indiegogo and other crowdfunding sites.   A simple, clean look.  I just want the goal, countdown and donate button.   I don't want the screen cluttered up with other stuff.    When they click the donate button then we need to show them all the other detail fields they need to fill in.

Does that make sense?
- Gordon

**Comment by mathetos** [comment]
I understand. This isn't an issue really for this add-on as much as a custom snippet request for Give Core really. I can throw something together for you. I'll follow-up on this later today.

**Comment by gordoncsmith** [comment]
The Countdown module isn't of use to me unless the goal is on the same page.   I suspect that many users who want Hickstarter-like functionality are ini the same boat.
Thanks,
- Gordon

**Comment by DevinWalker** [comment]
Closing as this isn't a place for support requests.
