### ISSUE TITLE
fix(form-countdown): resolve incompatibility with Give core 2.1

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Form-Countdown#29]
## Issue Overview

The plugin doesn't appear to be working with 2.1 at all. Forms are not closed at the end of the countdown, and the clock JS throws an error.

## Expected Behavior
I expect it to work.

## Steps to Reproduce (for bugs)
1. Enable a form countdown as well as the clock.
2. View the form on the front end. 
3. Once the form is set to close, view the form again.
4. It will still be open, and the clock JS throws an error.

**Comment by Benunc** [comment]
Please test this on PHP 7.2, it's still broken there.

**Comment by ravinderk** [comment]
@Benunc issue has been fixed
