### ISSUE TITLE
Add a countdown clock

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Form-Countdown#4]
Part of the appeal of this Addon is that it can help create a sense of "Urgency" for the donors to give before the time runs out. 

Let's give the Admins the ability to add a simple Countdown clock to add to their form to reinforce that sense of urgency.

Here's a really solid and easy to implement one:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html

I would imagine for first release the Form Edit setting would just be a simple radio buttons: 

**Countdown Clock:**     Enable | Disable

**Comment by mathetos** [comment]
We could also add an option to put the clock in certain positions of the donation form, like so:

**Clock Position:**   * Sidebar (if enabled)  * Under Title  *  Under Donation Amount  *  Under Payment Fields

**Comment by mathetos** [comment]
This is another really slick one, but it's in "Beta". @ravinderk it's up to you which you think will be better for implementation:

http://flipclockjs.com/

**Comment by mathetos** [comment]
Last detail, I think the clock should NOT show at all once the duration has been achieved, regardless of what position on the form it is in. Some users might like showing it as all zeros but for now let's just remove it upon completion.

**Comment by ravinderk** [comment]
@mathetos According to current logic here are all time constraints which we are supporting in version `1.0`:
weeks (optional), days (optional), hours, minutes, seconds

You can show hide option time constraints with filters.
for ref: https://github.com/WordImpress/Give-Form-Countdown/blob/master/template/countdown_clock_1.php#L17

**Example code:**
```
function ravs_test( $time_constraints ) {
	// $time_constraints = array();
	// $time_constraints = array( 'days' );
	// $time_constraints = array( 'weeks', 'days' );
	// $time_constraints = array( 'weeks' );

	return $time_constraints;
}
add_filter( 'gfc_25_countdown_clock_1_time_constraints', 'ravs_test' );
```

You can also change countdown clock with action and filters.
for ref: https://github.com/WordImpress/Give-Form-Countdown/blob/master/includes/actions.php#L61

Let me know if you want to update some thing?

**Comment by mathetos** [comment]
No, I think it's fine for now to just have a basic Enable/Disable. As long as it counts down from either the number of days, or the specific date then we're good. 

Maybe I'm missing it, but currently the Countdown doesn't actually count-down yet, right?

**Comment by ravinderk** [comment]
@mathetos Is it working fine?
