### ISSUE TITLE
Syncing the relationship between Duration and Goal Achieved better

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Form-Countdown#5]
Site admins might want to also support a Goal on forms with a Duration. The question is how would the "Goal Complete" message relate to the Duration End message?

**My suggestion is the following:**

Add a "Use Donation End Message" option in the "Donation Goal" tab like so:

![image](https://cloud.githubusercontent.com/assets/930724/23043254/89d42a9a-f450-11e6-82b5-1966aa49f545.png)

If they say "No", then the default "Goal Achieved" option appears for them to set their message.
![image](https://cloud.githubusercontent.com/assets/930724/23043333/c1ab44da-f450-11e6-97f3-758816916b7a.png)

Saying "No" means that if the Goal is achieved before the end of the campaign, then this message will appear, until the Donation Duration ends and then THAT message will appear instead.

Saying "Yes" means that whether the Goal is achieved OR the Duration ends, only the Donation Duration message will appear.

Also if they say "No", then in the "Donation Duration" tab, the message option should be disabled, and instructions appear, like so:

![image](https://cloud.githubusercontent.com/assets/930724/23043526/71ca4a32-f451-11e6-8355-f351359983b3.png)

**Comment by ravinderk** [comment]
@mathetos you can check master branch for this issue and let me know if you found any bug or want to improve something

**Comment by ravinderk** [comment]
@mathetos Instead of creating `Yes/No` settings, I followed `Give` core terminology and use `Enabled/Disbaled`

**Comment by mathetos** [comment]
Hmmm... this is _mostly_ working, but I think we need to test every combination correctly.

## GOAL ENABLED, DONATIONS END MESSAGE DISABLED
![image](https://cloud.githubusercontent.com/assets/930724/23247360/8277c902-f94e-11e6-826a-9fc4d838f401.png)

- [ ] If the Goal is reached before the Duration ends, it should show the Goal Message
- [ ] If the Goal is NOT reached before the Duration ends, but the Duration ends, it should show the Duration end message

## GOAL ENABLED, DONATIONS END MESSAGE ENABLED
- [ ] If the Goal is reached before the Duration ends, it should show the Duration End message
- [ ] If the Goal is NOT reached before the Duration ends, but the Duration ends, it should show the Duration end message.

## GOAL CLOSED DISABLED, DONATIONS END MESSAGE ENABLED
- [ ] If the Goal is reached before the Duration ends, it should not show anything (except maybe the Countdown clock)
- [ ] If the Goal is NOT reached before the Duration ends, but the Duration ends, it should show the Duration end message.

**Comment by mathetos** [comment]
I just reviewed and so far it seems like NONE of those items above are true. So we gotta work on that logic.

**Comment by mathetos** [comment]
Reviewed again and this looks resolved. Great work @ravinderk !
