### ISSUE TITLE
Duration achieved message position

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Form-Countdown#8]
Site admins might not want to completely close the form when the duration is over. Let's give them some additional options.

**Duration achieved message**
* Close the form and replace its content
* Keep the form open and show this message above the form 
* Keep the form open and show this message below the form

NOTE that if they choose to show the message ABOVE the form, it should show directly below the form title.

**Comment by ravinderk** [comment]
@mathetos you can check master branch for this issue and let me know if you found any bug or want to improve something

**Comment by mathetos** [comment]
Tested. Looks good to go. Thanks!
